# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dist_in <- function(distribution, set_n, set_mean, set_sd) {
    .Call('_indtermdigit_dist_in', PACKAGE = 'indtermdigit', distribution, set_n, set_mean, set_sd)
}

data_in <- function(distribution, set_n, set_mean, set_sd, duplicates) {
    .Call('_indtermdigit_data_in', PACKAGE = 'indtermdigit', distribution, set_n, set_mean, set_sd, duplicates)
}

violation <- function(sample_0, duplicates, type) {
    .Call('_indtermdigit_violation', PACKAGE = 'indtermdigit', sample_0, duplicates, type)
}

perm_basic <- function(distribution, duplicates, set_n, set_mean, set_sd, decimals, reps, times, tolerance) {
    .Call('_indtermdigit_perm_basic', PACKAGE = 'indtermdigit', distribution, duplicates, set_n, set_mean, set_sd, decimals, reps, times, tolerance)
}

perm_do <- function(sample_0, decimals, reps, tolerance) {
    .Call('_indtermdigit_perm_do', PACKAGE = 'indtermdigit', sample_0, decimals, reps, tolerance)
}

average_fre <- function(x) {
    .Call('_indtermdigit_average_fre', PACKAGE = 'indtermdigit', x)
}

average_fre2 <- function(x, n) {
    .Call('_indtermdigit_average_fre2', PACKAGE = 'indtermdigit', x, n)
}

ft_stat <- function(new_n, vec_1_frac, vec_2_frac) {
    .Call('_indtermdigit_ft_stat', PACKAGE = 'indtermdigit', new_n, vec_1_frac, vec_2_frac)
}

rms_stat <- function(new_n, vec_1_frac, vec_2_frac) {
    .Call('_indtermdigit_rms_stat', PACKAGE = 'indtermdigit', new_n, vec_1_frac, vec_2_frac)
}

chisq_stat <- function(draws, vec_1_frac, vec_2_frac) {
    .Call('_indtermdigit_chisq_stat', PACKAGE = 'indtermdigit', draws, vec_1_frac, vec_2_frac)
}

g2_stat <- function(draws, vec_1_frac, vec_2_frac) {
    .Call('_indtermdigit_g2_stat', PACKAGE = 'indtermdigit', draws, vec_1_frac, vec_2_frac)
}

int_dec <- function(s, decimals) {
    .Call('_indtermdigit_int_dec', PACKAGE = 'indtermdigit', s, decimals)
}

full_vec <- function(int_1, dec_1) {
    .Call('_indtermdigit_full_vec', PACKAGE = 'indtermdigit', int_1, dec_1)
}

actual_frac <- function(int_full, dec, new_n) {
    .Call('_indtermdigit_actual_frac', PACKAGE = 'indtermdigit', int_full, dec, new_n)
}

tab_it <- function(x, bins, a, b) {
    .Call('_indtermdigit_tab_it', PACKAGE = 'indtermdigit', x, bins, a, b)
}

perm_vector <- function(v, r_sum, c_sum) {
    .Call('_indtermdigit_perm_vector', PACKAGE = 'indtermdigit', v, r_sum, c_sum)
}

expected_cells <- function(r_frac, c_frac) {
    .Call('_indtermdigit_expected_cells', PACKAGE = 'indtermdigit', r_frac, c_frac)
}

out_vector_cpp <- function(c_sums) {
    .Call('_indtermdigit_out_vector_cpp', PACKAGE = 'indtermdigit', c_sums)
}

